name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código
        uses: actions/checkout@v4.1.5

      - name: Autenticação no Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da Imagem Docker
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src  # O diretório onde o seu código-fonte está
          file: ./src/Dockerfile  # O caminho para o Dockerfile
          push: true  # Envia a imagem para o Docker Hub
          tags: |
            brendofut/aula-primeira-pipeline:v${{ github.run_number }}
            brendofut/aula-primeira-pipeline:latest
